# -------------------------------------------------------
# 공통 변수
# t3.medium 검증: gpu_enabled: false
# g4dn 전환 시:   gpu_enabled: true  ← 이것만 바꾸면 됨
# -------------------------------------------------------
gpu_enabled: false

k8s_version: "1.29"
pod_cidr: "192.168.0.0/16"   # Calico 기본 CIDR

ecr_region: "ap-northeast-2"
model_bucket: "microlens-model-weights"
